### PR TITLE
add biblio-style for biblatex 

### PR DESCRIPTION
**Pull request by XiangyunHuang**

### CODE REVIEW

**Comment by XiangyunHuang** [comment]
thanks, I see

**Comment by XiangyunHuang** [comment]
However, there is a error, when I use the template from pandoc

```
This is XeTeX, Version 3.14159265-2.6-0.99998 (TeX Live 2017) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
! Dimension too large.
<to be read again> 
                   p
l.134 \begin{document}
```

The .tex file generated by bookdown is here

<https://raw.githubusercontent.com/XiangyunHuang/master-thesis-template/master/master-thesis-template.tex>

I can not figure it out what is wrong?

**Comment by yihui** [comment]
Could you please not use the raw link? Just use the normal Github link to the file. That way, I can see the line numbers. Thanks!

**Comment by XiangyunHuang** [comment]
Finally, I think I find the problem, in my `preamble.tex` file, 
```
% 设置英文字体为 Times New Roman
\usepackage[T1]{fontenc}
\usepackage{mathptmx}
```
The key is above two lines , I just want to set font as ` Times New Roman` ，but it bites me!
Is there any other way?

**Comment by XiangyunHuang** [comment]
I have solved the problem just now, only one option change

```
\usepackage[T1]{fontenc}
```

to

```
\usepackage[OT1]{fontenc}
```

**Pull request closed without merging**
