### PR TITLE
Updated the SiM template

### PR DESCRIPTION
**Pull request by ellessenne**
Hi,
I updated the template for Statistics in Medicine for a greater adherence to its LaTeX class. 
The template knits fine on my side, as before some tests do not succeed.
Thanks!

### CODE REVIEW

**Comment by ellessenne** [comment]
I am puzzled by the `mathtime` package requirement: it renders on MiKTeX (tested on Windows 7), not on TeXLive (tested on OS X 10.11.6) - or is it just me?

**Comment by jjallaire** [comment]
The tests are actually also failing for me on OS X with this error:

```
output file: Untitled.knit.md

! LaTeX Error: File `mathtime.sty' not found.

! Emergency stop.
<read *> 
```

I think we need to remove the mathtime.sty requirement (or somehow bundle it) since we want our templates to work out of the box on an OS X LaTeX installation. Could you submit another PR with this change?

**Comment by ellessenne** [comment]
Thanks @jjallaire, I will do that asap!

**Comment by jjallaire** [comment]
I am hoping to submit to CRAN soon but am waiting on your change. If you can't make it over the next couple of days I'll just unexport this format for the time being. Let me know.

**Comment by ellessenne** [comment]
I will have access to a Mac for testing on Monday, would that be too late?

**Comment by jjallaire** [comment]
Yup, that would be fine!

**Pull request merged**
