### PR TITLE
[WIP] First attempt at arXiv template

### PR DESCRIPTION
**Pull request by alexpghayes**
Taking a crack #235 but running into issues with the template.

----

To contribute a new article template to this package, please make sure you have done the following things (note that `journalname_article` below is only an example name):

- [x] Unless you have done it in any other RStudio's projects before, please sign the [individual](https://rstudioblog.files.wordpress.com/2017/05/rstudio_individual_contributor_agreement.pdf) or [corporate](https://rstudioblog.files.wordpress.com/2017/05/rstudio_corporate_contributor_agreement.pdf) contributor agreement for a significant pull request (it is fine not to sign it if a PR is only intended to fix a few typos). You can send the signed copy to <jj@rstudio.com>.

- [x] Add the `journalname_article()` function to `R/article.R` if the output format is simple enough, otherwise create a separate `R/journalname_article.R`.

- [x] Add the Pandoc LaTeX template `inst/rmarkdown/templates/journalname_article/resources/template.tex`.

- [x] Add a skeleton article `inst/rmarkdown/templates/journalname_article/skeleton/skeleton.Rmd`.

- [x] Add a description of the template `inst/rmarkdown/templates/journalname_article/template.yaml`.

- [x] Please include the document class file (`*.cls`) if needed, but please do not include standard LaTeX packages (`*.sty`) that can be downloaded from CTAN. Please keep the number of new files absolutely minimal, and also make examples minimal (e.g., if you need a `.bib` example, try to only leave one or two bibliography entries in it, and don't include one hundred items in it without using all of them).

**NOTE**: I don't think `arxiv` is on CTAN from a cursory search, but my LaTeX awareness isn't high enough to confirm this. For the time being I'm going operate under the assumption that `arxiv.sty` is necessary and belongs where it is.

- [x] Update Rd and namespace (could be done by `devtools::document()`).

- [x] Update NEWS.

- [x] Update README with a link to the newly supported journal.

- [x] Add a test to `tests/testit/test-formats.R`.

- [x] Add your name to the list of authors `Authors@R` in DESCRIPTION. You don't need to bump the package version in DESCRIPTION.

### CODE REVIEW

**Comment by alexpghayes** [comment]
- [ ] Figure out how the template is licensed and if/how to list George Kour in `DESCRIPTION`

**Comment by kevinykuo** [comment]
@alexpghayes What's blocking this? Would be really cool to have!

**Comment by alexpghayes** [comment]
Other projects have taken priority / I'm suffering through raw LaTeX for the paper I was going to use this for. Please feel free to finish this off, it's probably going to be a while before I can get to this.

**Comment by kevinykuo** [comment]
Looks mostly fine to me :P

I'll get going on a manuscript and see if I hit anything.

**Comment by kevinykuo** [comment]
OK I'm stuck. Can't seem to figure out how to use numeric style for citations. I've tried both (separately)
```
\usepackage[style=numeric]{biblatex}
```

and

```
\usepackage[numbers]{natbib}
```

directly in the template to no avail. Let me know if y'all have any tips...

**Comment by kevinykuo** [comment]
Oops, `citation_package` in the header, all good now.

**Comment by kevinykuo** [comment]
@alexpghayes @yihui I made my way through a short paper, and have made the following changes to make things work:

In `template.tex`, I added the following block

```
$for(include-before)$
$include-before$
$endfor$
```

In my .Rmd yaml, I have

```
header-includes: |
  \usepackage{makecell}
  \usepackage{amsmath}
  \usepackage[numbers]{natbib}
  \bibliographystyle{abbrvnat}
  \usepackage{graphicx}
  \usepackage{mathtools}
  \usepackage{lmodern}
output: 
  bookdown::pdf_book:
    base_format: rticles::arxiv_article
    citation_package: natbib
```

Questions: should some of these packages be hardcoded into the template (if so, which ones)? Also, is there a better way to handle bibliography options?

**Comment by alexpghayes** [comment]
I don't know. What are next steps here? Should I close this PR, or incorporate these updates, or...?

**Comment by kevinykuo** [comment]
The most efficient way to proceed is probably for @yihui to opine on whether any changes I made locally should be part of the template, then @alexpghayes can push a commit if needed and we can merge?

**Comment by mark-fangzhou-xie** [comment]
I believe it would be very nice to have arxiv template for this. I wonder if there is any update on this or is there any guide I can follow to use this arxiv template in R Markdown?

Thank you very much!

**Comment by kevinykuo** [comment]
@yihui Let's merge this and I can open a follow-up PR to add my changes.

**Pull request merged**
