### PR TITLE
Adding the Taylor & Francis journal template

### PR DESCRIPTION
**Pull request by dleutnant**
To contribute a new article template to this package, please make sure you have done the following things (note that `journalname_article` below is only an example name):

- [x] Unless you have done it in any other RStudio's projects before, please sign the [individual](https://rstudioblog.files.wordpress.com/2017/05/rstudio_individual_contributor_agreement.pdf) or [corporate](https://rstudioblog.files.wordpress.com/2017/05/rstudio_corporate_contributor_agreement.pdf) contributor agreement for a significant pull request (it is fine not to sign it if a PR is only intended to fix a few typos). You can send the signed copy to <jj@rstudio.com>.

- [x] Add the `journalname_article()` function to `R/journalname_article.R`. If the article needs CSL to process citations, see the function `acm_article()` for an example; otherwise see `asa_article()` for an example. If you don't know what CSL means, see the latter.

- [x] Add the Pandoc LaTeX template `inst/rmarkdown/templates/journalname_article/resources/template.tex`.

- [x] Add a skeleton article `inst/rmarkdown/templates/journalname_article/skeleton/skeleton.Rmd`.

- [x] Add a description of the template `inst/rmarkdown/templates/journalname_article/template.yaml`.

- [x] Please include the document class file (`*.cls`) if needed, but please do not include standard LaTeX packages (`*.sty`) that can be downloaded from CTAN.

- [x] Update Rd and namespace (could be done by `devtools::document()`).

- [x] Update NEWS.

- [x] Update README with a link to the newly supported journal.

- [x] Add a test to `tests/testit/test-formats.R`.

- [x] Add your name to the list of authors `Authors@R` in DESCRIPTION. You don't need to bump the package version in DESCRIPTION.

Thank you!

### CODE REVIEW

**Comment by dleutnant** [comment]
My printer don't want me to print anything so, I will hand in the contributor agreement later:-)

**Comment by dleutnant** [comment]
Contributor agreement is on its way.

**Comment by dleutnant** [comment]
Thank you @yihui! I made the required changes. 
The `skeleton.Rmd` is indeed quite heavy, but I tried to be as close to the original LaTeX template as possible. Do you want me to substitute the body with sth. like the default `rmarkdown::pdf_document` template?

**Comment by yihui** [comment]
Do you know how to resolve conflicts in git? Your master branch has conflicts with the master branch here. BTW, it is strongly recommended that you use a different branch for each PR, and don't use the master branch.

**Comment by dleutnant** [comment]
OK, I'll open a new PR.

**Comment by dleutnant** [comment]
new PR is now #218.

**Pull request closed without merging**
