### PR TITLE
Add OpenMind article template

### PR DESCRIPTION
**Pull request by mikabr**
This adds an `rticles::opmi_article()` template based on the [OpenMind LaTeX template](https://www.mitpressjournals.org/journals/opmi/sub).

### CODE REVIEW

**Comment by mikabr** [comment]
sorry about that, will fix when I get a chance

**Comment by yihui** [comment]
No worries. Thanks!

**Comment by mikabr** [comment]
I redid the PR with #305 because this one was so messy

**Comment by yihui** [comment]
Thank you very much!

**Pull request closed without merging**
