### PR TITLE
Add support for multiple affiliations per author in the plos example

### PR DESCRIPTION
**Pull request by BlackEdder**

### CODE REVIEW

**Comment by lnalborczyk** [comment]
Hello,

I am not sure how to specify multiple affiliations per author. I have tried separating them by commas or spaces but it does not seem to work... any idea ?

Thanks !

**Comment by BlackEdder** [comment]
> I am not sure how to specify multiple affiliations per author in the PLOS template. I have tried separating them by commas or spaces but it does not seem to work... any idea ?

You add them as completely separate objects. See [skeleton.Rmd](https://github.com/rstudio/rticles/blob/master/inst/rmarkdown/templates/plos_article/skeleton/skeleton.Rmd) for an example

**Comment by lnalborczyk** [comment]
Thank you for your answer. There is no multiple affiliations _per author_ in the this .Rmd file however... here is what I do in the YAML of my file:

```
author:
  - name: Ladislas Nalborczyk
    affiliation: 1, 2 # 1 2 also does not work
    address: Laboratoire de Psychologie et NeuroCognition, Univ. Grenoble Alpes, 1251 avenue centrale, Grenoble, France
    email: ladislas.nalborczyk@univ-grenoble-alpes.fr
    corresponding: ladislas.nalborczyk@univ-grenoble-alpes.fr

address:
  - code: 1
    address: Univ. Grenoble Alpes, CNRS, LPNC, 38000 Grenoble, France
  - code: 2
    address: Department of Experimental Clinical and Health Psychology, Ghent University
```

But this does not work (only the fist affiliation appears). Do you know how to display both affiliations aside my name?

**Comment by BlackEdder** [comment]
Sorry I misread and thought that you were talking about authors ;)

Multiple affiliations need to be given as an array. Arrays in YAML are defined as: https://symfony.com/doc/current/components/yaml/yaml_format.html#collections. So either form below should work:

```
affiliation: [1,2]
```

or

```
affiliation: 
  - 1
  - 2
```

**Comment by lnalborczyk** [comment]
That works perfectly, thank you!

By the way, I am used to cross-reference Tables and Figures in RMarkdown using `\@ref(fig:label)` but this does not seem to work with this template (cf. screenshot below)...

Screenshot 2019-09-20 at 10 37 14

Any idea why?

**Comment by BlackEdder** [comment]
It should work... Do you define the table before referencing it?

**Comment by lnalborczyk** [comment]
The problem did not come from the order... but replacing 

```
output:
  rticles::plos_article:
  latex_engine: lualatex
```

by

```
output:
    bookdown::pdf_book:
      base_format: rticles::plos_article
      latex_engine: lualatex
```

solved it!

Thank you for your help!

**Comment by lnalborczyk** [comment]
Sorry, I still have another question for which I have not found an answer either in the documentation or in previous issues... PLOS ONE requires figures to be uploaded separately from the manuscript.

Is there an easy way to remove figures from the manuscript? Maybe an argument such as `figsintext: false` in the YAML header?

**Pull request merged**
