### PR TITLE
Update peerj article citation format

### PR DESCRIPTION
**Pull request by zkamvar**
I have updated the PeerJ article citation format to be more pandoc-tic.

### CODE REVIEW

**Comment by jjallaire** [comment]
@yihui Does this look okay to you?

**Comment by yihui** [comment]
@zkamvar What is the requirement of citations in PeerJ? Does it disallow natbib or biblatex? I don't think using pandoc-citeproc is a good idea for LaTeX/PDF output.

**Comment by zkamvar** [comment]
@yihui There are [no explicit citation requirements for PeerJ](https://peerj.com/about/author-instructions/). While this change sets pandoc-citeproc as the default, it does not exclude natbib or biblatex as possibilities (due to the additions to [template.tex](https://github.com/rstudio/rticles/pull/134/files#diff-67a4d3359ec7587bf447c8f7b9d839f9)). I can change the `citation_package` argument default back to "natbib" if you would like.

The previous iteration of `peerj_article()` [hard-coded natbib in the cls file](https://github.com/rstudio/rticles/pull/134/files#diff-0017d0466549c61e517440d6823b2468L45), which caused problems when attempting to use other options. 

For reference here is the citation with

 - pandoc-citeproc:
   
image

 - natbib

image

 - biblatex

image

**Comment by zkamvar** [comment]
Any update on this?

**Comment by zkamvar** [comment]
ping

**Pull request merged**
