### PR TITLE
Copernicus template update to v7.1

### PR DESCRIPTION
**Pull request by RLumSK**
Another update to the newest Copernicus template version from September 26 2022.
@nuest 

- [X] Update Rd and namespace (could be done by `devtools::document()`).

- [X] Update NEWS.

- [X] Update README with a link to the newly supported journal. Please add your Github username and the full name of the journal (follow other examples in the list).

### CODE REVIEW

**Comment by RLumSK** [comment]
Note: the failed test is not related to my changes.

**Comment by nuest** [comment]
Thanks @RLumSK - looks great to me. If needed I'm happy to double check locally, but the changes seem pretty straightforward.

**Comment by RLumSK** [comment]
@nuest and @cderv: In the meantime, Copernicus bump their version to 7.1. Since the 6.9 PR was not yet merged, I put it on top of it. This means now the update to the Copernicus template 7.1.

**Review by cderv — APPROVED** [review]
Sorry I was out for a few months. I am scaling back and ready 100% next year. 

LGTM. Thank you !

**Comment by RLumSK** [comment]
@cderv No worries, and thanks! Merry Christmas!

**Pull request merged**
