### PR TITLE
Update Copernicus publication template to version 6.2

### PR DESCRIPTION
**Pull request by RLumSK**
This PR updates the Copernicus publication template to the version published 2021-01-15  and add NEWs. I also tested the output and it looks good to me.

To contribute a new article template to this package, please make sure you have done the following things (note that `journalname_article` below is only an example name):

- [X] Update NEWS.

### CODE REVIEW

**Review by cderv — APPROVED** [review]
Thank you ! 

The CI error is the same as what we have in https://github.com/rstudio/rmarkdown/issues/2011 and it is not related. So I'll merge

**Comment by cderv** [comment]
One advice for next time @RLumSK : if you remember, please work on a branch before making your PR. It is easier for us to handle PR that are not on master branch. There is no issue really, just better for me to handle PR that are not made on your master. (and easier for you to update your fork after a PR also) . Thank you!

**Comment by RLumSK** [comment]
> One advice for next time @RLumSK : if you remember, please work on a branch before making your PR. It is easier for us to handle PR that are not on master branch. There is no issue really, just better for me to handle PR that are not made on your master. (and easier for you to update your fork after a PR also) . Thank you!

@cderv Sorry about that. Sure, no problem at all, next time I will do as advised. In particular the latter part "and easier for you to update your fork after a PR also" is indeed an aspect I did not think about before.

**Comment by cderv** [comment]
If you are into **usethis**, the PR helper can help you deal with all that from R
https://usethis.r-lib.org/articles/articles/pr-functions.html

**Pull request merged**
