### PR TITLE
Update Copernicus template to version 6.1

### PR DESCRIPTION
**Pull request by RLumSK**
This PR includes the already announced final fix for #331, which was released by Copernicus today in the morning.

- [X] Unless you have done it in any other RStudio's projects before, please sign the [individual](https://rstudioblog.files.wordpress.com/2017/05/rstudio_individual_contributor_agreement.pdf) or [corporate](https://rstudioblog.files.wordpress.com/2017/05/rstudio_corporate_contributor_agreement.pdf) contributor agreement for a significant pull request (it is fine not to sign it if a PR is only intended to fix a few typos). You can send the signed copy to <jj@rstudio.com>.

- [X] Update NEWS.

### CODE REVIEW

**Comment by cderv** [comment]
Great ! Have you tested it on previous and newer version of Latex ? Do you know if it is expected to work with new and old version ? 
Just wondering if we should watch out for that.

**Comment by cderv** [comment]
From my test it is working ok !

**Comment by cderv** [comment]
Thank you @RLumSK !

**Comment by RLumSK** [comment]
@cderv Sorry, I should have mentioned this little but important detail: Yes, of course, I had tested it before the PR. I've tried TeXLive 2015 to 2020, and all worked. Besides, before I created the PR, I was in contact with Copernicus because they had also asked me to test the new version + they tested it on their end. Hence, I would say: It should be fine.

**Comment by cderv** [comment]
Awesome! Thank you a lot!

**Pull request merged**
