### PR TITLE
ASA journal style

### PR DESCRIPTION
**Pull request by hadley**
This looks good from my end. What else do you need for rticles?

### CODE REVIEW

**Comment by jjallaire** [comment]
Could you add a test here (https://github.com/rstudio/rticles/blob/master/tests/testthat/test_formats.R#L42) once this is ready to go. I usually like to run these tests on all platforms before merging b/c the distinct LaTeX environments can easily create incompatibilities.

**Comment by hadley** [comment]
I refactored `test_format()` — it didn't work with `asa_article` because `output_file` was a full path, rather than a file name. I couldn't quite figure out what you were trying to do, but I think I've captured the intent and simplified the code a little (and all the tests pass for me)

**Comment by hadley** [comment]
(I also alphabetised the test formats so it's more obvious where you should add your test)

**Comment by jjallaire** [comment]
Looks good, thanks!

**Pull request merged**
